export const IPC_CHANNELS = {
  PROJECT_CREATE: "project:create",
  PROJECT_OPEN: "project:open",
  PROJECT_SAVE: "project:save",
  PROJECT_SELECT_CREATE_DIRECTORY: "project:selectCreateDirectory",
  PROJECT_SELECT_OPEN_LOCATION: "project:selectOpenLocation",
  STORY_SCRIPT_SELECT_IMPORT_FILE: "storyScript:selectImportFile",
  STORY_SCRIPT_SAVE_TEMPLATE: "storyScript:saveTemplate",
  MEDIA_PROBE: "media:probe",
  MEDIA_IMPORT_FILES: "media:importFiles",
  MEDIA_SELECT_FILES: "media:selectFiles",
  MEDIA_EXTRACT_FRAME: "media:extractFrame",
  MEDIA_EXTRACT_PREVIEW_FRAME: "media:extractPreviewFrame",
  MEDIA_EXPORT_TIMELINE_CLIPS: "media:exportTimelineClips",
  MEDIA_RENDER_TIMELINE: "media:renderTimeline",
  NATIVE_MEDIA_OPEN_ASSET: "nativeMedia:openAsset",
  NATIVE_MEDIA_PROBE: "nativeMedia:probe",
  NATIVE_MEDIA_DECODE_FRAME: "nativeMedia:decodeFrame",
  NATIVE_MEDIA_CREATE_PLAYBACK_SESSION: "nativeMedia:createPlaybackSession",
  NATIVE_MEDIA_SEEK: "nativeMedia:seek",
  NATIVE_MEDIA_PLAY: "nativeMedia:play",
  NATIVE_MEDIA_PAUSE: "nativeMedia:pause",
  NATIVE_MEDIA_RENDER_FRAME: "nativeMedia:renderFrame",
  NATIVE_MEDIA_RENDER_AUDIO: "nativeMedia:renderAudio",
  NATIVE_MEDIA_ENCODE_TIMELINE: "nativeMedia:encodeTimeline",
  NATIVE_MEDIA_DISPOSE: "nativeMedia:dispose",
  APP_CONFIG_GET: "appConfig:get",
  APP_CONFIG_SAVE: "appConfig:save",
  AI_GENERATE_VIDEO: "ai:generateVideo",
  AI_GENERATE_STORYBOARD: "ai:generateStoryboard",
  AI_STORYBOARD_PROGRESS: "ai:storyboardProgress",
  AI_REPLACE_RANGE: "ai:replaceRange",
  AI_GET_JOB_STATUS: "ai:getJobStatus"
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
